.github/workflows/e2e.yml

ci: introduce operator caching

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/epic-tracker.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/release-tracker.md
.github/PULL_REQUEST_TEMPLATE.md

Added PR and issue templates based on those found in ibc-go

chore: added PR and issue templates

---

e2e/interchaintestv8/chainconfig/chain_config.go

switch to ibc-go eureka branch simapp

---

.github/workflows/abigen.yaml

fix: abigen ci workflow

---

e2e/interchaintestv8/chainconfig/chain_config.go

feat/ibc-eureka merged the ABI encoding support, so switching to the correct upstream image.
closes: #XXXX
---

chore: update to feat/ibc-eureka simapp image

---

.github/workflows/e2e.yml
e2e/interchaintestv8/relayer_test.go

feat(e2e): added relayer tests for batched txs and acknowledgements

---

.github/workflows/e2e.yml
e2e/interchaintestv8/relayer_test.go

test(e2e): added timeout tests for the relayer

---

packages/relayer-lib/src/tx_builder/eth_eureka.rs
packages/utils/src/rpc.rs
programs/operator/src/runners/fixtures/membership.rs
programs/operator/src/runners/fixtures/uc_and_mem.rs

refactor: refactored duplicate tendermint proof queries

---

contracts/light-clients/SP1ICS07Tendermint.sol

docs: remove repetitive words

---

.github/workflows/e2e.yml
.github/workflows/rust.yml
e2e/interchaintestv8/relayer_test.go

test: added test case for concurrent relayer requests

---

.github/workflows/e2e.yml
e2e/interchaintestv8/e2esuite/suite.go
e2e/interchaintestv8/e2esuite/utils.go
e2e/interchaintestv8/relayer/config.go
e2e/interchaintestv8/relayer/config.tmpl
e2e/interchaintestv8/relayer_test.go
packages/relayer-lib/src/tx_builder/eth_to_cosmos.rs
packages/relayer-lib/src/utils/cosmos.rs
programs/relayer/src/modules/eth_to_cosmos.rs

imp(relayer): enable mock relaying

---

.github/workflows/e2e.yml
contracts/ICSCore.sol

imp: used the same client sequence for all client types

---

.github/workflows/e2e.yml
e2e/interchaintestv8/ibc_eureka_test.go

test(e2e): added test case for error acknowledgements

---

packages/ethereum/ethereum-light-client/README.md

fix: typo in README.md
This pull request fixes a typographical error in the `README.md` file:
- Replaced "implemention" with "implementation" to correct the spelling mistake.
- Corrected the typo in the description of the Ethereum Light Client section.
- N/A (or reference any related issues if applicable)
- This update ensures the documentation is more accurate and professional.

docs: fix typo in README.md

---

.github/workflows/e2e.yml
.gitignore
justfile
packages/sp1-ics07-tendermint-prover/build.rs
packages/sp1-ics07-tendermint-prover/src/programs.rs

chore: move elfs to default target and run full CI every 3 days

---

README.md
contracts/utils/ICS20Lib.sol

docs: benchmarks updated

---

e2e/interchaintestv8/e2esuite/light_clients.go
e2e/interchaintestv8/types/ethereum/types.gen.go
flake.nix
packages/ethereum/ethereum-light-client/src/client_state.rs
packages/ethereum/ethereum-light-client/src/error.rs
packages/ethereum/ethereum-light-client/src/lib.rs
packages/ethereum/ethereum-light-client/src/misbehaviour.rs
packages/ethereum/ethereum-light-client/src/test_utils/fixtures/TestICS20TransferERC20TokenfromEthereumToCosmosAndBack_Groth16.json
packages/ethereum/ethereum-light-client/src/test_utils/fixtures/TestICS20TransferNativeCosmosCoinsToEthereumAndBack_Groth16.json
packages/ethereum/ethereum-light-client/src/test_utils/fixtures/TestICS20TransferTimeoutFromEthereumToCosmosChain_Groth16.json
packages/ethereum/ethereum-light-client/src/verify.rs
programs/cw-ics08-wasm-eth/src/contract.rs
programs/cw-ics08-wasm-eth/src/error.rs
programs/cw-ics08-wasm-eth/src/msg.rs
programs/cw-ics08-wasm-eth/src/query.rs
programs/cw-ics08-wasm-eth/src/sudo.rs

feat: added misbehavior to ethereum light client

---

scripts/deploymentConfig.json

chore: remove accidential files

---

.github/workflows/abigen.yaml
.github/workflows/e2e.yml
e2e/interchaintestv8/.golangci.yml

chore: fix e2e linter config

---

contracts/ICS26Router.sol
contracts/errors/IICS24HostErrors.sol
contracts/errors/IICS26RouterErrors.sol
contracts/utils/IBCStoreUpgradeable.sol

closes: #285
closes: #290
closes: #289
---

refactor: refactor deletePacketCommitment and document commitment functions

---

README.md
abi/ICS26Router.json
abigen/ics26router/contract.go
contracts/ICS26Router.sol
contracts/interfaces/IICS26Router.sol
packages/relayer-lib/src/events/eureka.rs
packages/relayer-lib/src/utils/cosmos.rs
packages/relayer-lib/src/utils/eth_eureka.rs
test/solidity-ibc/ICS26RouterTest.t.sol
test/solidity-ibc/IntegrationTest.t.sol

imp: support indexing for ICS26Router events

---

e2e/interchaintestv8/cmd/.gitignore
e2e/interchaintestv8/cmd/README.md
e2e/interchaintestv8/cmd/relay_tx.go

This PR fixes the RELAYER_ADDRESS message
Adds a baseline README
Adds a gitignore for binaries
This repository uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

RELAYER_ADDRESS fix, README initial, gitignore

---

e2e/interchaintestv8/cmd/README.md
e2e/interchaintestv8/cmd/relay_tx.go

- Changes to the readme to walk through the process in a more step-by-step fashion. Including how to get ETH Sepolia testnet tokens and create an erc20 token.
- Also fixes some example addresses.
---

Update Devnet Guide Readme

---

e2e/interchaintestv8/cmd/.gitignore
e2e/interchaintestv8/cmd/README.md
e2e/interchaintestv8/cmd/utils/eth_helpers.go

Changes the README:
- updates terms
- adds the balance of Cosmos command
- adds the Cosmos->Eth command
Adds to .gitignore:
- the wasm client data each time a tx is made
Adds simple spinner during waiting times
- briandowns/spinner added for GetTxReciept in the eth util
<!--
This repository uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
---

README updates, gitignore, simple spinner addition

---

e2e/interchaintestv8/go.mod
e2e/interchaintestv8/go.sum

adds github.com/briandowns/spinner to go mod and sum
---

fix: add spinner go.mod and go.sum

---

programs/relayer/config.example.json

Fixes address in the example config (40 bytes instead of 32).
---

fix(relayer): input properly formatted address in the example config

---

.github/workflows/abigen.yaml
.github/workflows/docker.yml
.github/workflows/e2e.yml
.github/workflows/foundry.yml
.github/workflows/rust.yml

ci: use depot runners for CI

---

e2e/interchaintestv8/cmd/README.md

This PR strips out the README, and points to the canonical docs.
Goes to the minimal README structure for getting going with the tool, everything else goes to source-of-truth documentation on skip go
https://docs.skip.build/go/eureka/devnet-testing-guide

Devenet deployment

---

flake.nix

Hi! I fixes a broken link in the flake.nix file. The outdated link to the SP1 installation documentation has been updated to point to the correct and current location. 
---

fix: update 404 link in `flake.nix`

---

e2e/interchaintestv8/cmd/README.md
e2e/interchaintestv8/cmd/transfer_from_eth_cmd.go

Remove branch instructions in readme since already on the branch

---

Cargo.lock
programs/relayer/Cargo.toml
programs/relayer/build.rs
programs/relayer/src/core/builder.rs
programs/relayer/src/lib.rs

This reverts commit f7f057de651d8f4390343a0925e3bd2540bb7d22.
It seems to cause all sorts of issues with both CI and actual using the relayer, so reverting for now.
closes: #XXXX
---

chore: revert feat(relayer): add basic health check and reflection service

---

contracts/light-clients/SP1ICS07Tendermint.sol

sherlock 161 + internal audit item
---

fix: harden trusting period

---

contracts/light-clients/SP1ICS07Tendermint.sol

imp: removed useless state modification

---

contracts/ICS20Transfer.sol
contracts/interfaces/IEscrow.sol
contracts/utils/Escrow.sol
contracts/utils/RateLimitUpgradeable.sol
test/solidity-ibc/EscrowTest.t.sol

fix: rate limits to track net outflows

---

README.md

chore: update gas benchmarks with latest changes

---

programs/cw-ics08-wasm-eth/src/contract.rs
programs/cw-ics08-wasm-eth/src/msg.rs
programs/cw-ics08-wasm-eth/src/query.rs
programs/cw-ics08-wasm-eth/src/sudo.rs

fix: set frozen state on misbehaviour

---

contracts/ICS20Transfer.sol
scripts/deployments/DeployProxiedICS20Transfer.sol
scripts/deployments/DeployProxiedICS26Router.sol
test/solidity-ibc/EscrowTest.t.sol
test/solidity-ibc/IBCAdminTest.t.sol
test/solidity-ibc/ICS20TransferTest.t.sol

imp: used `encodeCall` instead of `encodeWithSelector` when possible

---

.env.example
e2e/interchaintestv8/ibc_eureka_test.go
e2e/interchaintestv8/multichain_test.go
e2e/interchaintestv8/operator/operator.go
e2e/interchaintestv8/testvalues/values.go
programs/operator/src/cli/command.rs
programs/operator/src/runners/fixtures/membership.rs
programs/operator/src/runners/fixtures/misbehaviour.rs
programs/operator/src/runners/fixtures/uc_and_mem.rs
programs/operator/src/runners/fixtures/update_client.rs

test: add `--private-cluster` option to operator fixture generation

---

.env.example
.github/workflows/e2e-full.yml
.github/workflows/e2e-minimal.yml
e2e/interchaintestv8/operator/operator.go
e2e/interchaintestv8/testvalues/values.go
programs/operator/src/cli/command.rs
programs/operator/src/runners/operator.rs

Forgot to actually add this to the tests after it was made optional.
Also renamed the env variable xD
---

test: use private cluster in ci

---

abi/RelayerHelper.json
abigen/relayerhelper/contract.go
justfile

feat: add relayer helper abigen

---

.github/workflows/docker.yml

chore: add latest tag when pushing to main

---

.github/workflows/e2e-full.yml
e2e/interchaintestv8/relayer_test.go
programs/relayer/Dockerfile

test: fix e2e-full

---

programs/relayer/Dockerfile

fix: docker relayer entrypoint

---

e2e/interchaintestv8/cmd/README.md
e2e/interchaintestv8/cmd/main.go
e2e/interchaintestv8/cmd/relay_tx.go
e2e/interchaintestv8/cmd/transfer_from_cosmos_to_eth.go
e2e/interchaintestv8/cmd/transfer_from_eth_cmd.go
e2e/interchaintestv8/cmd/utils/eth_helpers.go
e2e/interchaintestv8/ethereum/ethereum.go
e2e/interchaintestv8/ibc_eureka_test.go
e2e/interchaintestv8/multichain_test.go
e2e/interchaintestv8/relayer_test.go
e2e/interchaintestv8/sp1_ics07_test.go

This PR changes over the env vars to the testnet implementation, and refactors away from the mock clients

Update to Testnet Params + moar Spinner Animations

---

packages/sp1-ics07-tendermint-prover/src/prover.rs

imp: remove verify step in sp1 prover

---

.gitignore
Cargo.lock
Cargo.toml
programs/relayer/Cargo.toml
programs/relayer/src/bin/relayer.rs
programs/relayer/src/core/builder.rs
programs/relayer/src/lib.rs
programs/relayer/src/metrics/mod.rs
scripts/ethgenesis/go.mod
scripts/ethgenesis/main.go

imp: add promethius metrics to relayer

---

README.md

docs: updated roles and benchmarks in README.md

---

.github/workflows/docker.yml

ci: fix relayer docker tag builds

---

.github/actions/e2e-setup/action.yml

ci: fix e2e-setup failure on cache hit

---

.github/workflows/release.yml

ci: only trigger on sp1-programs tag

---

justfile
programs/relayer/Dockerfile
scripts/relayer_docker_entrypoint.sh

only supports one binary version right now, but easily expandable to multiple when we'll need it
---

feat(ci): download SP1 binaries on demand

---

programs/relayer/Dockerfile
scripts/relayer_docker_entrypoint.sh

fix(relayer): pass arguments to script

---

.github/mergify.yml

ci: add mergify config

---

e2e/interchaintestv8/ibc_eureka_test.go
e2e/interchaintestv8/multichain_test.go
programs/relayer/src/modules/eth_to_cosmos.rs

chore: minor cleanup

---

.github/workflows/e2e-minimal.yml

ci: removed e2e-minimal cron

---

.github/workflows/abigen.yaml
.github/workflows/e2e-mock.yml
e2e/interchaintestv8/.golangci.yml

Migrates golangci-lint from v1.x to v2.x.
Automatic migration done with `golangci-lint migrate` as per https://golangci-lint.run/product/migration-guide
---

chore: migrate golangci-lint to v2

---

.github/workflows/docker.yml

ci: add workflow dispatch to docker workflow

---

flake.nix

Added rust devenv tools to nix (`rust-analyzer`, `rustfmt`, `clippy`).
---

chore: rust nix devenv

---

.env.example
.github/workflows/foundry.yml

ci: updated env variables

---

.gitignore
packages/key-utils/src/lib.rs
programs/ibc-attestor/src/adapter_impls/arbitrum.rs
programs/ibc-attestor/src/attestation_store.rs
programs/ibc-attestor/src/attestor.rs
programs/ibc-attestor/src/cli.rs
programs/ibc-attestor/src/signer.rs
proto/ibc-attestor/attestation.proto
proto/ibc-attestor/ibc-attestor.proto

Co-authored-by: Gjermund Garaba <gjermund@garaba.net>
closes: IBC-134
I decided to just put the endpoints in `todo!()` to unblock integration work. Let me know how you feel about that.
---

feat: update attestation grpc api

---

.gitignore

chore: gitignore .code-workspace files

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

I expect the number of AI/drive-by PRs to increase, so I want to have a contribution guideline in place similar to the one we have in [ibc-go](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md)
closes: #XXXX
---

chore: add contribution guidelines and code of conduct

---

.github/workflows/rust.yml
programs/cw-ics08-wasm-eth/src/contract.rs

chore: fix clippy complaints

---

programs/solana/programs/ics26-router/src/instructions/client.rs
programs/solana/programs/ics26-router/src/state.rs
programs/solana/programs/ics26-router/src/test_utils.rs

closes: #650
closes: IBCSOL-258
---

fix: solana ibc inconsistencies

---

docs/adr/solana-storage-architecture.md

Solana storage ADR
Closes IBCSOL-243
---

chore: solana storage adr

---

docs/logging.md

docs: add logging best practices

---

docs/metrics.md

docs: add metrics best practices

---

flake.lock
flake.nix

chore: add slither to nix flake

---

flake.nix

adds rust with lsp and tooling to solana devshell
---

add rust in solana devshell for lsp access

---

bun.lock
justfile
package.json

chore: updated openzeppelin, forge-std, and solhint

---

e2e/interchaintestv8/.golangci.yml
e2e/interchaintestv8/chainconfig/genesis.go
e2e/interchaintestv8/chainconfig/kurtosis.go
e2e/interchaintestv8/cosmos_relayer_test.go
e2e/interchaintestv8/e2esuite/grpc_query.go
e2e/interchaintestv8/e2esuite/suite.go
e2e/interchaintestv8/e2esuite/utils.go
e2e/interchaintestv8/ethereum/ethereum.go
e2e/interchaintestv8/ibc_eureka_test.go
e2e/interchaintestv8/multichain_test.go
e2e/interchaintestv8/relayer_test.go
e2e/interchaintestv8/testvalues/values.go
e2e/interchaintestv8/types/tendermint_light_client_fixtures.go
e2e/interchaintestv8/types/tendermint_light_client_fixtures/membership.go
e2e/interchaintestv8/types/tendermint_light_client_fixtures/update_client.go

chore: update interchaintest in `golangci-lint`

---

e2e/interchaintestv8/e2esuite/utils.go

fix(e2e): support custom address prefix

---

e2e/interchaintestv8/chainconfig/ethereum.go
e2e/interchaintestv8/e2esuite/light_clients.go
e2e/interchaintestv8/e2esuite/suite.go
e2e/interchaintestv8/ibc_attestor_test.go

chore(demo): redundant WasmType and TestnetType variables

---

e2e/interchaintestv8/demo_test.go

test(e2e): full bridge transfer test from cosmos to eth

---

Dockerfile

refactor: expose metric port

---

packages/relayer/core/src/builder.rs

refactor: use permissive cors

---

test/solidity-ibc/ICS20TransferTest.t.sol
test/solidity-ibc/Integration2Test.t.sol
test/solidity-ibc/utils/IntegrationEnv.sol
test/solidity-ibc/utils/TestHelper.sol

test: refactor ICS20TransferTest
